-- The tags a project uses on its media.
--
-- Per-asset tags already exist as assets.tags (text[]). What did not exist was
-- a REGISTRY — "the tags this project uses" — so the Media Manager module had
-- nothing to offer an admin as a choice. This is that list.
--
-- Shaped after public.asset_categories, which is the same kind of thing and
-- already gets the tenant scoping right.
--
-- BOTH tenant columns are mandatory (CLAUDE.md landmine 12). lib/projectScope.js
-- decides whether to stamp a tenant by probing the table for project_id AND
-- owner_user_id; a table carrying only project_id fails that probe and
-- scopedInsertRow then silently stops stamping EITHER column. The insert still
-- succeeds, nothing errors, and the rows land with no tenant at all — which is
-- how 550 production rows ended up untenanted on 2026-08-16.

begin;

create table if not exists public.asset_tags (
  id            bigint      generated by default as identity primary key,
  tag           text        not null,
  project_id    text        null,
  owner_user_id text        null,
  created_at    timestamptz not null default now()
);

-- Uniqueness is PER PROJECT and case-insensitive: two tenants may both have a
-- "Courts" tag, and one tenant must not end up with "Courts" and "courts" as
-- separate entries — a list that splits like that is useless within a month.
create unique index if not exists idx_asset_tags_project_tag
  on public.asset_tags (project_id, lower(tag));

create index if not exists idx_asset_tags_project_id
  on public.asset_tags (project_id);

-- RLS on with no policies, matching the 2026-08-17 lockdown: the service key
-- bypasses RLS, and nothing else should reach this table directly.
alter table public.asset_tags enable row level security;

commit;
