-- Asset associations: link an asset to campaigns, messaging items, pages, etc.
-- Apply manually per environment (no migration runner).

create table if not exists public.asset_associations (
  id              bigint generated by default as identity primary key,
  asset_id        bigint      not null,
  target_type     text        not null,
  target_id       text        not null,
  target_label    text        not null default '',
  project_id      text        null,
  owner_user_id   text        null,
  created_at      timestamptz not null default now()
);

create index if not exists idx_asset_associations_asset_id
  on public.asset_associations (asset_id);

create index if not exists idx_asset_associations_project_id
  on public.asset_associations (project_id);

create unique index if not exists idx_asset_associations_unique_target
  on public.asset_associations (
    asset_id,
    target_type,
    target_id,
    coalesce(project_id, '')
  );
