-- messaging_tags table

create table if not exists public.messaging_tags (
  id bigint generated by default as identity primary key,
  tag text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_messaging_tags_tag
  on public.messaging_tags (tag);

create or replace function public.set_messaging_tags_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_messaging_tags_updated_at on public.messaging_tags;
create trigger trg_messaging_tags_updated_at
before update on public.messaging_tags
for each row
execute function public.set_messaging_tags_updated_at();
