create table if not exists public.messaging_prompts (
  id bigint generated by default as identity primary key,
  format text not null,
  topic text,
  prompt_kind text,
  prompt_text text not null,
  project_id text,
  owner_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_messaging_prompts_project_created
  on public.messaging_prompts (project_id, created_at desc);

create or replace function public.set_messaging_prompts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_messaging_prompts_updated_at on public.messaging_prompts;

create trigger trg_messaging_prompts_updated_at
before update on public.messaging_prompts
for each row
execute function public.set_messaging_prompts_updated_at();
