-- Object associations: link ANY two objects to each other.
--
-- This supersedes asset_associations, which could only express
-- "asset -> something" because its source side was a hard-typed asset_id.
-- Here both sides are described the same way (a type plus a text id), so
-- tweet -> hashtag and tweet -> tag are expressible alongside tweet -> image.
--
-- A link is stored ONCE, with the two sides in canonical order: the side
-- whose "type:id" string sorts first becomes side A. That is what makes the
-- unique index below able to reject the same pair saved in either direction.
-- lib/objectAssociationsStore.js applies the same ordering before writing.
--
-- Ids are text on both sides because the app mixes integer ids (assets,
-- messaging content, builder pages) with app-generated text ids (campaigns,
-- contacts, segments). See lib/associationTypes.js for the type registry.
--
-- Apply manually per environment (no migration runner).

create table if not exists public.object_associations (
  id              bigint generated by default as identity primary key,
  a_type          text        not null,
  a_id            text        not null,
  a_label         text        not null default '',
  b_type          text        not null,
  b_id            text        not null,
  b_label         text        not null default '',
  project_id      text        null,
  owner_user_id   text        null,
  created_at      timestamptz not null default now()
);

-- One row per pair per project. Canonical ordering (applied by the store)
-- means A->B and B->A collide here instead of creating a duplicate link.
create unique index if not exists idx_object_associations_unique_pair
  on public.object_associations (
    a_type,
    a_id,
    b_type,
    b_id,
    coalesce(project_id, '')
  );

-- Lookups run from either side, so both need their own index.
create index if not exists idx_object_associations_a_side
  on public.object_associations (project_id, a_type, a_id);

create index if not exists idx_object_associations_b_side
  on public.object_associations (project_id, b_type, b_id);


-- ---------------------------------------------------------------------------
-- Backfill from asset_associations.
--
-- Safe to re-run: "on conflict do nothing" skips rows already carried over.
-- The old table is left untouched so it can serve as a fallback for one
-- release; drop it only after the new panel has been in production a while.
-- ---------------------------------------------------------------------------

with legacy as (
  select
    'asset'::text     as x_type,
    aa.asset_id::text as x_id,
    ''::text          as x_label,
    aa.target_type    as y_type,
    aa.target_id      as y_id,
    aa.target_label   as y_label,
    aa.project_id,
    aa.owner_user_id,
    aa.created_at
  from public.asset_associations aa
  where aa.asset_id is not null
    and coalesce(aa.target_type, '') <> ''
    and coalesce(aa.target_id, '')   <> ''
),
ordered as (
  select
    (x_type || ':' || x_id) <= (y_type || ':' || y_id) as x_first,
    legacy.*
  from legacy
)
insert into public.object_associations
  (a_type, a_id, a_label, b_type, b_id, b_label, project_id, owner_user_id, created_at)
select
  case when x_first then x_type  else y_type  end,
  case when x_first then x_id    else y_id    end,
  case when x_first then x_label else y_label end,
  case when x_first then y_type  else x_type  end,
  case when x_first then y_id    else x_id    end,
  case when x_first then y_label else x_label end,
  project_id,
  owner_user_id,
  created_at
from ordered
on conflict do nothing;
