-- Influencer Clone Personas Subsystem Schema

DROP TABLE IF EXISTS public.influencer_persona_acquires CASCADE;
DROP TABLE IF EXISTS public.influencer_personas CASCADE;

-- Table: influencer_personas
CREATE TABLE public.influencer_personas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id TEXT, -- Binds strictly to native auth session context natively
  base_name TEXT NOT NULL,
  clone_name TEXT,
  clone_handle TEXT,
  primary_sources JSONB DEFAULT '[]'::jsonb,
  agent_email TEXT,
  status TEXT DEFAULT 'Provisioning' CHECK (status IN ('Provisioning', 'Active', 'Paused', 'Restricted')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: influencer_persona_acquires
CREATE TABLE public.influencer_persona_acquires (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id BIGINT REFERENCES public.influencer_personas(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  source_id TEXT,
  transformed_asset_id BIGINT,
  post_status TEXT DEFAULT 'pending' CHECK (post_status IN ('pending', 'processing', 'scheduled', 'posted', 'failed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Establish Row Level Security (RLS)
ALTER TABLE public.influencer_personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.influencer_persona_acquires ENABLE ROW LEVEL SECURITY;

-- Owner Policies
CREATE POLICY "Users govern their own proxy personas" 
  ON public.influencer_personas
  FOR ALL
  USING (auth.uid()::text = owner_id)
  WITH CHECK (auth.uid()::text = owner_id);

CREATE POLICY "Acquire blocks are bound dynamically to persona structure" 
  ON public.influencer_persona_acquires
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.influencer_personas p 
      WHERE p.id = influencer_persona_acquires.persona_id 
      AND p.owner_id = auth.uid()::text
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.influencer_personas p 
      WHERE p.id = influencer_persona_acquires.persona_id 
      AND p.owner_id = auth.uid()::text
    )
  );

/* Utility index block securely */
CREATE INDEX idx_persona_acquires_asset on public.influencer_persona_acquires(transformed_asset_id);
CREATE INDEX idx_persona_acquires_status on public.influencer_persona_acquires(post_status);
