-- acquire_youtube_details table
-- Stores one row per YouTube video detail acquire run.
-- Naming convention: acquire_[source]_[specifics]

create table if not exists public.acquire_youtube_details (
  run_id text primary key,
  video_url text not null,
  video_id text not null default '',
  topic text not null default '',
  tags text not null default '',
  title text not null default '',
  channel_name text not null default '',
  transcript_status text not null default 'unavailable',
  transcript_source text not null default 'none',
  transcript_provider text not null default 'youtube-native',
  request_json jsonb not null default '{}'::jsonb,
  result_json jsonb not null default '{}'::jsonb,
  project_id text null,
  owner_user_id text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists acquire_youtube_details_created_at_idx
  on public.acquire_youtube_details (created_at desc);

create index if not exists acquire_youtube_details_transcript_status_idx
  on public.acquire_youtube_details (transcript_status);

create index if not exists acquire_youtube_details_topic_idx
  on public.acquire_youtube_details (topic);

create index if not exists idx_acquire_youtube_details_project_id
  on public.acquire_youtube_details (project_id);

-- acquire_youtube_topics table
-- Stores reusable topic labels for the Acquire YouTube workflow.

create table if not exists public.acquire_youtube_topics (
  id bigint generated by default as identity primary key,
  topic text not null unique,
  project_id text null,
  owner_user_id text null,
  created_at timestamptz not null default now()
);

create index if not exists acquire_youtube_topics_topic_idx
  on public.acquire_youtube_topics (topic);

create index if not exists idx_acquire_youtube_topics_project_id
  on public.acquire_youtube_topics (project_id);

-- acquire_youtube_comments table
-- Stores one row per YouTube comment acquire run.

create table if not exists public.acquire_youtube_comments (
  run_id text primary key,
  video_url text not null,
  video_id text not null default '',
  title text not null default '',
  channel_name text not null default '',
  comment_count integer not null default 0,
  request_json jsonb not null default '{}'::jsonb,
  result_json jsonb not null default '{}'::jsonb,
  project_id text null,
  owner_user_id text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists acquire_youtube_comments_created_at_idx
  on public.acquire_youtube_comments (created_at desc);

create index if not exists idx_acquire_youtube_comments_project_id
  on public.acquire_youtube_comments (project_id);

-- acquire_youtube_videos table
-- Canonical one-row-per-video index used by the Acquire YouTube repository.

create table if not exists public.acquire_youtube_videos (
  video_record_id text primary key,
  video_url text not null default '',
  video_id text not null default '',
  title text not null default '',
  channel_name text not null default '',
  channel_url text not null default '',
  description text not null default '',
  hashtags text not null default '',
  topic text not null default '',
  tags text not null default '',
  thumbnail_url text not null default '',
  transcript_status text not null default 'unavailable',
  transcript_source text not null default 'none',
  transcript_provider text not null default 'youtube-native',
  detail_run_id text not null default '',
  comment_run_id text not null default '',
  miner_run_id text not null default '',
  research_run_id text not null default '',
  comment_count integer not null default 0,
  project_id text null,
  owner_user_id text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists acquire_youtube_videos_updated_at_idx
  on public.acquire_youtube_videos (updated_at desc);

create index if not exists acquire_youtube_videos_video_id_idx
  on public.acquire_youtube_videos (video_id);

create index if not exists acquire_youtube_videos_topic_idx
  on public.acquire_youtube_videos (topic);

create index if not exists idx_acquire_youtube_videos_project_id
  on public.acquire_youtube_videos (project_id);
