-- harvest_youtube_details table
-- Stores one row per YouTube video detail harvest run.
-- Naming convention: harvest_[source]_[specifics]

create table if not exists public.harvest_youtube_details (
  run_id text primary key,
  video_url text not null,
  video_id text not null default '',
  category text not null default '',
  tags text not null default '',
  title text not null default '',
  channel_name text not null default '',
  transcript_status text not null default 'unavailable',
  transcript_source text not null default 'none',
  transcript_provider text not null default 'youtube-native',
  request_json jsonb not null default '{}'::jsonb,
  result_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists harvest_youtube_details_created_at_idx
  on public.harvest_youtube_details (created_at desc);

create index if not exists harvest_youtube_details_transcript_status_idx
  on public.harvest_youtube_details (transcript_status);

alter table public.harvest_youtube_details
  add column if not exists category text not null default '';

alter table public.harvest_youtube_details
  add column if not exists tags text not null default '';

create index if not exists harvest_youtube_details_category_idx
  on public.harvest_youtube_details (category);

-- harvest_youtube_categories table
-- Stores reusable category labels for the YouTube harvest workflow.

create table if not exists public.harvest_youtube_categories (
  id bigint generated by default as identity primary key,
  category text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists harvest_youtube_categories_category_idx
  on public.harvest_youtube_categories (category);

-- harvest_youtube_comments table
-- Stores one row per YouTube comment harvest run.

create table if not exists public.harvest_youtube_comments (
  run_id text primary key,
  video_url text not null,
  video_id text not null default '',
  title text not null default '',
  channel_name text not null default '',
  comment_count integer not null default 0,
  request_json jsonb not null default '{}'::jsonb,
  result_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists harvest_youtube_comments_created_at_idx
  on public.harvest_youtube_comments (created_at desc);

-- harvest_youtube_videos table
-- Canonical one-row-per-video index used by the Acquire YouTube repository.

create table if not exists public.harvest_youtube_videos (
  video_record_id text primary key,
  video_url text not null default '',
  video_id text not null default '',
  title text not null default '',
  channel_name text not null default '',
  channel_url text not null default '',
  description text not null default '',
  hashtags text not null default '',
  category text not null default '',
  tags text not null default '',
  thumbnail_url text not null default '',
  transcript_status text not null default 'unavailable',
  transcript_source text not null default 'none',
  transcript_provider text not null default 'youtube-native',
  detail_run_id text not null default '',
  comment_run_id text not null default '',
  miner_run_id text not null default '',
  research_run_id text not null default '',
  comment_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists harvest_youtube_videos_updated_at_idx
  on public.harvest_youtube_videos (updated_at desc);

create index if not exists harvest_youtube_videos_video_id_idx
  on public.harvest_youtube_videos (video_id);

create index if not exists harvest_youtube_videos_category_idx
  on public.harvest_youtube_videos (category);

-- Migration: rename old tables to new names if they exist
-- Run this once against your existing Supabase project.
-- Safe to run even if old tables don't exist (DO blocks handle it gracefully).

do $$
begin
  if exists (
    select from information_schema.tables
    where table_schema = 'public' and table_name = 'youtube_harvest_runs'
  ) then
    alter table public.youtube_harvest_runs rename to harvest_youtube_details;
    raise notice 'Renamed youtube_harvest_runs -> harvest_youtube_details';
  end if;
end $$;

do $$
begin
  if exists (
    select from information_schema.tables
    where table_schema = 'public' and table_name = 'youtube_comment_harvest_runs'
  ) then
    alter table public.youtube_comment_harvest_runs rename to harvest_youtube_comments;
    raise notice 'Renamed youtube_comment_harvest_runs -> harvest_youtube_comments';
  end if;
end $$;

-- Rename old indexes if they exist (Postgres doesn't rename indexes automatically on table rename)
do $$
begin
  if exists (select from pg_indexes where indexname = 'youtube_harvest_runs_created_at_idx') then
    alter index public.youtube_harvest_runs_created_at_idx rename to harvest_youtube_details_created_at_idx;
  end if;
  if exists (select from pg_indexes where indexname = 'youtube_harvest_runs_transcript_status_idx') then
    alter index public.youtube_harvest_runs_transcript_status_idx rename to harvest_youtube_details_transcript_status_idx;
  end if;
end $$;
