create table if not exists public.website_peers (
  id bigint generated by default as identity primary key,
  site_type text not null default 'peer' check (site_type in ('source', 'peer')),
  source_url text not null default '',
  source_domain text not null default '',
  site_url text not null default '',
  domain text not null default '',
  title text not null default '',
  website_model text not null default '',
  matched_keywords text[] not null default '{}',
  snippet text not null default '',
  notes text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  project_id text null,
  owner_user_id text null,
  last_acquired_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_website_peers_project_id
  on public.website_peers(project_id);

create index if not exists idx_website_peers_domain
  on public.website_peers(domain);

create index if not exists idx_website_peers_source_domain
  on public.website_peers(source_domain);

create unique index if not exists idx_website_peers_project_site_scope
  on public.website_peers(project_id, site_type, source_domain, domain);

create or replace function public.set_website_peers_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_website_peers_updated_at on public.website_peers;

create trigger trg_website_peers_updated_at
before update on public.website_peers
for each row
execute function public.set_website_peers_updated_at();
