'use strict';

/**
 * Theme Wizard API — Phase 1 (foundation).
 *
 * Spec: docs/THEME_WIZARD_SPEC.md. The wizard proposes three complete looks for
 * a site, the operator ranks them, and later rounds build on the winner.
 *
 * WHAT PHASE 1 IS: the plumbing, with no AI in it. /generate queues a job and
 * seeds three placeholder candidates so the whole path — queue, poll, compare,
 * rank, apply, revert — can be exercised end to end before a single token is
 * spent. Phase 2 replaces seedPlaceholderCandidates() with the real generator
 * and nothing else here has to move.
 *
 * AUTH: staff-only for v1 (spec §2, "agency-only ... build the guardrails now").
 * Requires a platform app_session (centralized in routes/index.js), and
 * '/api/builder/theme-wizard' sits in PROJECT_ADMIN_SESSION_DENY_PREFIXES so
 * tenant project-admin sessions cannot reach it.
 */

const { parseJsonBody, sendOk, sendErr } = require('./http');
const { requestProjectScope } = require('../lib/requestProjectScope');
const { checkEndpointLimit } = require('../lib/rateLimiter');
const { listPages, updatePage } = require('../lib/builderPagesStore');
const { createTheme } = require('../lib/builderThemesStore');
const store = require('../lib/themeWizardStore');

const PREFIX = '/api/builder/theme-wizard';

const SEED_TYPES = ['current_pages', 'external_url', 'brand_kit', 'brief'];

function requireProject(req, res) {
  const scope = requestProjectScope(req);
  if (!scope.projectId) {
    sendErr(res, 400, 'An active project is required (x-project-id header)', { code: 'PROJECT_REQUIRED' });
    return null;
  }
  return scope;
}

/**
 * Phase 1 stand-in for the generator. Three fixed directions, deliberately far
 * apart, so the compare screen is exercised with looks that actually differ —
 * the real generator has the same obligation for a harder reason (hazards
 * 4.3/4.4: variety has to be engineered into the prompt because the sampling
 * knobs are gone and the model's own default is the same every time).
 *
 * The rationale text says out loud that these are placeholders. Nobody should
 * be able to mistake a plumbing test for a generated theme.
 */
const PLACEHOLDER_DIRECTIONS = [
  {
    direction: 'High-contrast editorial — near-black on white, one accent',
    themePatch: {
      primaryColor: '#111111',
      secondaryColor: '#4A4A4A',
      backgroundColor: '#FFFFFF',
      accentColor: '#C8102E',
      typography: { fonts: { heading: 'Georgia, serif', body: 'Helvetica, Arial, sans-serif' } },
    },
  },
  {
    direction: 'Cool technical — slate ground, restrained blue accent',
    themePatch: {
      primaryColor: '#1F2933',
      secondaryColor: '#52606D',
      backgroundColor: '#F5F7FA',
      accentColor: '#2B6CB0',
      typography: { fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' } },
    },
  },
  {
    direction: 'Warm organic — deep green on sand, amber accent',
    themePatch: {
      primaryColor: '#22331F',
      secondaryColor: '#5A6B54',
      backgroundColor: '#F2EDE3',
      accentColor: '#D08C34',
      typography: { fonts: { heading: 'Fraunces, serif', body: 'Source Sans Pro, sans-serif' } },
    },
  },
];

async function seedPlaceholderCandidates({ sessionId, projectId, round, parentCandidateId }, scope) {
  const created = [];
  for (let index = 0; index < PLACEHOLDER_DIRECTIONS.length; index += 1) {
    const preset = PLACEHOLDER_DIRECTIONS[index];
    // Sequential rather than parallel: the (session, round, slot) unique
    // constraint makes a partial parallel insert hard to reason about, and
    // three rows is not worth the concurrency.
    const result = await store.createCandidate({
      sessionId,
      projectId,
      round,
      slot: index + 1,
      direction: preset.direction,
      rationale: 'PLACEHOLDER — generated by the Phase 1 stand-in, not by a model. '
        + 'Real rationales arrive with the generator in Phase 2.',
      themePatch: preset.themePatch,
      parentCandidateId: parentCandidateId || '',
    }, scope);
    if (!result.ok) return result;
    created.push(result.data);
  }
  return { ok: true, status: 201, data: created };
}

async function handleGenerate(req, res, sessionId, scope) {
  if (checkEndpointLimit(req, res, 'themeWizard.generate')) return true;

  const sessionResult = await store.getSession(sessionId, scope);
  if (!sessionResult.ok) return sendErr(res, sessionResult.status || 404, sessionResult.error || 'Session not found'), true;
  const session = sessionResult.data;

  const body = await parseJsonBody(req);
  const round = session.roundCount + 1;
  const parentCandidateId = String(body?.parentCandidateId || '').trim();

  const jobResult = await store.createJob({
    sessionId,
    projectId: scope.projectId,
    ownerUserId: scope.userId,
    type: 'generate_round',
    input: { round, parentCandidateId, lockedValues: session.lockedValues || {} },
    status: 'running',
    startedAt: new Date().toISOString(),
  }, scope);
  if (!jobResult.ok) return sendErr(res, jobResult.status || 500, jobResult.error || 'Could not queue generation'), true;
  const job = jobResult.data;

  // Phase 1 finishes the work inline because seeding three fixed rows is
  // instant. The job row still exists and still transitions, so the UI's
  // queue-and-poll path is real from day one — Phase 2 moves the work to a
  // worker without the client noticing (hazard 4.2).
  const seeded = await seedPlaceholderCandidates({
    sessionId, projectId: scope.projectId, round, parentCandidateId,
  }, scope);

  if (!seeded.ok) {
    await store.updateJob(job.id, {
      status: 'failed',
      error: seeded.error || 'Could not create candidates',
      finishedAt: new Date().toISOString(),
    }, scope);
    return sendErr(res, seeded.status || 500, seeded.error || 'Could not create candidates'), true;
  }

  await store.updateSession(sessionId, { roundCount: round }, scope);
  const finished = await store.updateJob(job.id, {
    status: 'succeeded',
    finishedAt: new Date().toISOString(),
  }, scope);

  return sendOk(res, 202, {
    job: finished.ok ? finished.data : job,
    round,
    candidates: seeded.data,
  }), true;
}

/**
 * Apply is the dangerous one. It merges the candidate's theme into every
 * landing page and template in the project — the same bulk-rewrite shape as the
 * canonical-section save that wiped the Marinoff menu (hazard 4.1). Two rules
 * hold here and must keep holding:
 *
 *   1. Snapshot first, and abort the whole apply if the snapshot fails.
 *   2. Await every page write. The 2026-07-22 propagation bug was a
 *      fire-and-forget loop that the serverless freeze killed after 30 of 50
 *      pages; a caller that waits gets a real failure instead of silent drift.
 */
async function handleApply(req, res, candidateId, scope) {
  // Read the body once, up front — the request stream cannot be re-parsed
  // after the awaits below.
  const body = await parseJsonBody(req);

  const candidateResult = await store.getCandidate(candidateId, scope);
  if (!candidateResult.ok) return sendErr(res, candidateResult.status || 404, candidateResult.error || 'Candidate not found'), true;
  const candidate = candidateResult.data;

  const pagesResult = await listPages(5000, scope);
  if (!pagesResult.ok) return sendErr(res, pagesResult.status || 500, pagesResult.error || 'Could not load pages'), true;
  const pages = Array.isArray(pagesResult.data) ? pagesResult.data : [];
  if (!pages.length) return sendErr(res, 400, 'This project has no pages to apply a theme to', { code: 'NO_PAGES' }), true;

  // Rule 1 — snapshot before anything is written.
  const snapshot = await store.createApplySnapshot({
    sessionId: candidate.sessionId,
    label: `Theme Wizard — before applying "${candidate.direction}"`,
    pages,
  }, scope);
  if (!snapshot.ok) {
    return sendErr(res, snapshot.status || 500,
      `Nothing was changed: the safety snapshot failed (${snapshot.error || 'unknown error'})`,
      { code: 'SNAPSHOT_FAILED' }), true;
  }

  const themePatch = candidate.themePatch && typeof candidate.themePatch === 'object' ? candidate.themePatch : {};
  const themeName = String(body?.name || '').trim()
    || `Theme Wizard — ${candidate.direction}`.slice(0, 255);

  const themeResult = await createTheme({ name: themeName, ...themePatch }, scope);
  if (!themeResult.ok) return sendErr(res, themeResult.status || 500, themeResult.error || 'Could not save the theme'), true;

  // Rule 2 — awaited, and pageBackground is carried through explicitly so the
  // merge cannot drop it (hazard 4.6).
  const typography = themePatch.typography && typeof themePatch.typography === 'object' ? themePatch.typography : null;
  const results = await Promise.all(pages.map(async (page) => {
    const existingTheme = page.theme && typeof page.theme === 'object' ? page.theme : {};
    const mergedTheme = typography ? { ...existingTheme, typography } : existingTheme;
    const updated = await updatePage(String(page.id), {
      layoutSections: page.layoutSections,
      pageBackground: page.pageBackground,
      theme: mergedTheme,
    }, scope);
    return { id: page.id, name: page.name, ok: updated.ok, error: updated.error || null };
  }));

  const applied = results.filter((r) => r.ok).length;
  const failed = results.filter((r) => !r.ok);

  await store.updateSession(candidate.sessionId, {
    status: 'applied',
    appliedCandidateId: candidate.id,
    applySnapshotId: String(snapshot.data?.id || ''),
  }, scope);

  return sendOk(res, 200, {
    theme: themeResult.data,
    snapshotId: snapshot.data?.id || null,
    applied,
    failed: failed.length,
    // Named, not counted: "3 pages failed" is not actionable, "these three
    // pages failed" is.
    failures: failed.map((r) => ({ id: r.id, name: r.name, error: r.error })),
  }), true;
}

async function handleRevert(req, res, sessionId, scope) {
  const sessionResult = await store.getSession(sessionId, scope);
  if (!sessionResult.ok) return sendErr(res, sessionResult.status || 404, sessionResult.error || 'Session not found'), true;
  const session = sessionResult.data;

  const snapshot = await store.getApplySnapshot(session.applySnapshotId, scope);
  if (!snapshot.ok) {
    return sendErr(res, snapshot.status || 404,
      snapshot.error || 'This session has no snapshot to revert to', { code: 'NO_SNAPSHOT' }), true;
  }

  const snapshotPages = Array.isArray(snapshot.data?.pages) ? snapshot.data.pages : [];
  if (!snapshotPages.length) {
    return sendErr(res, 409, 'The snapshot for this session is empty; nothing was restored', { code: 'EMPTY_SNAPSHOT' }), true;
  }

  const results = await Promise.all(snapshotPages.map(async (snapPage) => {
    const pageId = String(snapPage?.id || '');
    if (!pageId) return { id: '', name: snapPage?.name || '', ok: false, error: 'missing id' };
    const restored = await updatePage(pageId, snapPage, scope);
    return { id: pageId, name: snapPage?.name || '', ok: restored.ok, error: restored.error || null };
  }));

  const restored = results.filter((r) => r.ok).length;
  const failed = results.filter((r) => !r.ok);

  // Only stand the session back up if everything came back. A partial restore
  // that reports 'active' would invite a second apply on top of a half-reverted
  // site.
  if (!failed.length) {
    await store.updateSession(sessionId, {
      status: 'active',
      appliedCandidateId: '',
      applySnapshotId: '',
    }, scope);
  }

  return sendOk(res, 200, {
    restored,
    failed: failed.length,
    failures: failed.map((r) => ({ id: r.id, name: r.name, error: r.error })),
    sessionStatus: failed.length ? 'applied' : 'active',
  }), true;
}

async function handle(req, res, pathname, method) {
  if (!pathname.startsWith(PREFIX)) return false;
  if (!req.authUser) return sendErr(res, 401, 'Not authenticated', { code: 'AUTH_REQUIRED' }), true;

  const scope = requireProject(req, res);
  if (!scope) return true;

  // POST /sessions — start a wizard run
  if (pathname === `${PREFIX}/sessions` && method === 'POST') {
    const body = await parseJsonBody(req);
    const seedType = String(body?.seedType || 'current_pages').trim();
    if (!SEED_TYPES.includes(seedType)) {
      return sendErr(res, 400, `Unknown seed type "${seedType}". Expected one of: ${SEED_TYPES.join(', ')}`, { code: 'VALIDATION_ERROR' }), true;
    }
    if (seedType !== 'current_pages') {
      return sendErr(res, 400, `The "${seedType}" starting point arrives in Phase 5; use "current_pages" for now`, { code: 'NOT_IMPLEMENTED' }), true;
    }
    const result = await store.createSession({
      seedType,
      seedPayload: body?.seedPayload || {},
      previewPageId: String(body?.previewPageId || '').trim(),
      ownerUserId: scope.userId,
    }, scope);
    if (!result.ok) return sendErr(res, result.status || 500, result.error || 'Could not start a wizard session'), true;
    return sendOk(res, 201, result.data), true;
  }

  // GET /sessions — list runs for the active project
  if (pathname === `${PREFIX}/sessions` && method === 'GET') {
    const result = await store.listSessions(scope);
    if (!result.ok) return sendErr(res, result.status || 500, result.error || 'Could not load sessions'), true;
    return sendOk(res, 200, result.data), true;
  }

  const sessionMatch = pathname.match(/^\/api\/builder\/theme-wizard\/sessions\/([^/]+)$/);
  const generateMatch = pathname.match(/^\/api\/builder\/theme-wizard\/sessions\/([^/]+)\/generate$/);
  const rankMatch = pathname.match(/^\/api\/builder\/theme-wizard\/sessions\/([^/]+)\/rank$/);
  const locksMatch = pathname.match(/^\/api\/builder\/theme-wizard\/sessions\/([^/]+)\/locks$/);
  const revertMatch = pathname.match(/^\/api\/builder\/theme-wizard\/sessions\/([^/]+)\/revert$/);
  const applyMatch = pathname.match(/^\/api\/builder\/theme-wizard\/candidates\/([^/]+)\/apply$/);
  const jobMatch = pathname.match(/^\/api\/builder\/theme-wizard\/jobs\/([^/]+)$/);

  // GET /sessions/:id — session plus every round and job
  if (sessionMatch && method === 'GET') {
    const sessionId = decodeURIComponent(sessionMatch[1] || '').trim();
    const sessionResult = await store.getSession(sessionId, scope);
    if (!sessionResult.ok) return sendErr(res, sessionResult.status || 404, sessionResult.error || 'Session not found'), true;
    const [candidates, jobs] = await Promise.all([
      store.listCandidates(sessionId, scope),
      store.listJobs(sessionId, scope),
    ]);
    return sendOk(res, 200, {
      session: sessionResult.data,
      candidates: candidates.ok ? candidates.data : [],
      jobs: jobs.ok ? jobs.data : [],
    }), true;
  }

  if (generateMatch && method === 'POST') {
    return handleGenerate(req, res, decodeURIComponent(generateMatch[1] || '').trim(), scope);
  }

  // GET /jobs/:id — poll generation status
  if (jobMatch && method === 'GET') {
    const jobId = decodeURIComponent(jobMatch[1] || '').trim();
    const result = await store.getJob(jobId, scope);
    if (!result.ok) return sendErr(res, result.status || 404, result.error || 'Job not found'), true;
    return sendOk(res, 200, result.data), true;
  }

  // POST /sessions/:id/rank — ranking plus per-candidate feedback
  if (rankMatch && method === 'POST') {
    const sessionId = decodeURIComponent(rankMatch[1] || '').trim();
    const body = await parseJsonBody(req);
    const rankings = Array.isArray(body?.rankings) ? body.rankings : [];
    if (!rankings.length) return sendErr(res, 400, 'rankings is required', { code: 'VALIDATION_ERROR' }), true;

    const sessionResult = await store.getSession(sessionId, scope);
    if (!sessionResult.ok) return sendErr(res, sessionResult.status || 404, sessionResult.error || 'Session not found'), true;

    const updated = [];
    for (const entry of rankings) {
      const candidateId = String(entry?.candidateId || '').trim();
      if (!candidateId) continue;
      // Re-read through the scoped getter so a candidate id from another
      // project cannot be ranked into this session.
      const existing = await store.getCandidate(candidateId, scope);
      if (!existing.ok || existing.data.sessionId !== sessionId) {
        return sendErr(res, 404, `Candidate ${candidateId} is not part of this session`, { code: 'CANDIDATE_MISMATCH' }), true;
      }
      const result = await store.updateCandidate(candidateId, {
        rank: entry?.rank,
        feedback: entry?.feedback,
      }, scope);
      if (!result.ok) return sendErr(res, result.status || 500, result.error || 'Could not save ranking'), true;
      updated.push(result.data);
    }
    return sendOk(res, 200, updated), true;
  }

  // POST /sessions/:id/locks — pin values a later round must not change
  if (locksMatch && method === 'POST') {
    const sessionId = decodeURIComponent(locksMatch[1] || '').trim();
    const body = await parseJsonBody(req);
    const lockedValues = body?.lockedValues && typeof body.lockedValues === 'object' ? body.lockedValues : {};
    const result = await store.updateSession(sessionId, { lockedValues }, scope);
    if (!result.ok) return sendErr(res, result.status || 500, result.error || 'Could not save locks'), true;
    return sendOk(res, 200, result.data), true;
  }

  if (applyMatch && method === 'POST') {
    return handleApply(req, res, decodeURIComponent(applyMatch[1] || '').trim(), scope);
  }

  if (revertMatch && method === 'POST') {
    return handleRevert(req, res, decodeURIComponent(revertMatch[1] || '').trim(), scope);
  }

  return sendErr(res, 405, 'Method not allowed', { code: 'METHOD_NOT_ALLOWED' }), true;
}

module.exports = {
  handle,
  manifest: {
    id: 'themeWizard',
    label: 'Theme Wizard',
    prefixes: [PREFIX],
  },
};
