import { describe, expect, it } from "vitest";

import { assetToAdminMediaItem, matchesFilters } from "./use-gallery-media-library";
import {
  DEFAULT_GALLERY_MEDIA_FILTERS,
  hasActiveGalleryMediaFilters,
  type GalleryMediaFilters
} from "../gallery-media-filters";
import { ADMIN_MEDIA_MANAGER_SOURCE } from "../admin-media-shared";

/**
 * The "Media Mgr" gallery filter. The point of the column behind it is that
 * an asset uploaded by hand, one imported from Drive, one generated by AI and
 * one pulled in by Site Import were previously indistinguishable once they
 * landed in the gallery.
 *
 * The case that matters most is the last one in each group: a row written
 * BEFORE the column existed carries '', and '' must never be mistaken for a
 * Media Manager upload — that would put a false claim in the one column whose
 * entire job is to be trusted.
 */

const filters = (over: Partial<GalleryMediaFilters> = {}): GalleryMediaFilters => ({
  ...DEFAULT_GALLERY_MEDIA_FILTERS,
  ...over
});

const item = (source?: string) => {
  const mapped = assetToAdminMediaItem({
    assetName: "photo.jpg",
    assetType: "Image",
    location: "https://blob.example/photo.jpg",
    source
  });
  if (!mapped) throw new Error("fixture asset did not map to a media item");
  return mapped;
};

describe("source travels from the asset row to the gallery item", () => {
  it("carries a recognised source through", () => {
    expect(item(ADMIN_MEDIA_MANAGER_SOURCE).source).toBe(ADMIN_MEDIA_MANAGER_SOURCE);
  });

  it("leaves source undefined for a row written before the column existed", () => {
    expect(item("").source).toBeUndefined();
    expect(item(undefined).source).toBeUndefined();
  });
});

describe("the Media Mgr filter", () => {
  it("is off by default, and passes everything", () => {
    expect(DEFAULT_GALLERY_MEDIA_FILTERS.mediaManagerOnly).toBe(false);
    expect(matchesFilters(item(ADMIN_MEDIA_MANAGER_SOURCE), filters(), "")).toBe(true);
    expect(matchesFilters(item(""), filters(), "")).toBe(true);
  });

  it("keeps Media Manager uploads when it is on", () => {
    expect(
      matchesFilters(item(ADMIN_MEDIA_MANAGER_SOURCE), filters({ mediaManagerOnly: true }), "")
    ).toBe(true);
  });

  it("drops an asset with no recorded origin when it is on", () => {
    expect(matchesFilters(item(""), filters({ mediaManagerOnly: true }), "")).toBe(false);
  });

  it("drops an asset from some other surface when it is on", () => {
    expect(matchesFilters(item("site-import"), filters({ mediaManagerOnly: true }), "")).toBe(false);
  });

  it("combines with another filter rather than replacing it", () => {
    const mediaManagerJpg = item(ADMIN_MEDIA_MANAGER_SOURCE);
    expect(
      matchesFilters(mediaManagerJpg, filters({ mediaManagerOnly: true, extension: ".jpg" }), "")
    ).toBe(true);
    expect(
      matchesFilters(mediaManagerJpg, filters({ mediaManagerOnly: true, extension: ".png" }), "")
    ).toBe(false);
  });

  it("counts as an active filter, so the Clear button appears", () => {
    expect(hasActiveGalleryMediaFilters(filters())).toBe(false);
    expect(hasActiveGalleryMediaFilters(filters({ mediaManagerOnly: true }))).toBe(true);
  });
});
