#!/usr/bin/env node
'use strict';
/**
 * Syntax gate for the hand-written browser JavaScript.
 *
 * WHY THIS EXISTS
 * Everything else in this repo gets parsed by something as a side effect of
 * normal work: the React builder is bundled by esbuild, and the server code in
 * routes/ and lib/ is `require`d by the node tests. `public/js/` is the one
 * place that is neither — those files are plain <script src> tags in
 * src/layout.html, they are excluded from tsconfig.json, and there is no
 * linter. So until this ran, the first thing to ever parse them was a user's
 * browser.
 *
 * That is not theoretical: pageHeadingNav.js sat on main unparseable for
 * months (three object keys missing their opening quote). A syntax error
 * discards the WHOLE file, so every back-link in the admin app silently did
 * nothing, and no check in the project noticed.
 *
 * WHAT IT CATCHES
 * Syntax errors only — the file-is-completely-dead class. It cannot see a
 * typo like `App.assset.foo()`, which parses fine and fails only when that
 * line runs. Catching those needs a linter, which is a much larger
 * conversation given ~98k lines of legacy vanilla JS.
 *
 * Parsing is done with esbuild (already a build dependency) because it handles
 * both ES modules and CommonJS in a single process — the whole sweep is well
 * under a tenth of a second.
 *
 * Usage:  node scripts/check_syntax.cjs [--quiet]
 */

const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const ROOT = path.resolve(__dirname, '..');
const QUIET = process.argv.includes('--quiet');

/**
 * Directories of hand-written browser JS. Generated bundles are skipped: they
 * are esbuild's own output, so a syntax error there would have failed the
 * build that produced them.
 */
const SCAN_DIRS = ['public/js', 'public/shared'];
const SKIP_FILES = new Set([
  'richtext-vendor.js', // generated by scripts/build_richtext_bundle.mjs
]);

function collect(dir) {
  const abs = path.join(ROOT, dir);
  if (!fs.existsSync(abs)) return [];
  return fs
    .readdirSync(abs, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.js') && !SKIP_FILES.has(entry.name))
    .map((entry) => path.join(dir, entry.name))
    .sort();
}

const files = SCAN_DIRS.flatMap(collect);
const failures = [];

for (const rel of files) {
  const source = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  try {
    esbuild.transformSync(source, { loader: 'js', sourcefile: rel });
  } catch (err) {
    const detail = err?.errors?.[0];
    failures.push({
      file: rel,
      message: detail?.text || err?.message || 'Unknown syntax error',
      line: detail?.location?.line,
      column: detail?.location?.column,
      lineText: detail?.location?.lineText,
    });
  }
}

if (!failures.length) {
  if (!QUIET) console.log(`[check:syntax] OK — ${files.length} browser JS file(s) parse cleanly.`);
  process.exit(0);
}

console.error(`\n[check:syntax] ${failures.length} file(s) will not parse.`);
console.error('A syntax error throws away the ENTIRE file, so everything it defines is dead in the browser.\n');
for (const failure of failures) {
  const where = failure.line ? `${failure.file}:${failure.line}:${failure.column ?? 0}` : failure.file;
  console.error(`  ${where}`);
  console.error(`    ${failure.message}`);
  if (failure.lineText) console.error(`    > ${failure.lineText.trim()}`);
  console.error('');
}
process.exit(1);
