#!/usr/bin/env node
'use strict';

/**
 * scripts/check_conventions.cjs — deterministic repo-convention checks.
 *
 * Default mode inspects the STAGED diff (runs from the pre-commit hook);
 * `--all` scans the working tree (for CI).
 *
 * Escape hatch: SKIP_CONVENTIONS=1 git commit ...   (or git commit --no-verify)
 * If you bypass, say so in the commit/PR description.
 *
 * Checks:
 *   1. No build artifacts staged — generated files are gitignored and must
 *      never be committed (Vercel/CI rebuild them from source).
 *   2. public/js/ freeze — no NEW .js files there (see public/js/CLAUDE.md).
 *   3. No <button>/<a> inside <th> (sort id goes on the <th> itself).
 *
 * Generated-file list: keep in sync with .gitignore ("Build artifacts"
 * block), CLAUDE.md, and scripts/hooks/block_generated_edits.cjs.
 */

const { execSync } = require('child_process');

const MODE_ALL = process.argv.includes('--all');
const failures = [];

function sh(cmd) {
  return execSync(cmd, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
}

function stagedFiles(filter) {
  const flag = filter ? ` --diff-filter=${filter}` : '';
  return sh(`git diff --cached --name-only${flag}`).split('\n').map((s) => s.trim()).filter(Boolean);
}

// ---------------------------------------------------------------------------
// 1. Build artifacts must never be committed
// ---------------------------------------------------------------------------

const GENERATED = [
  'public/app-shell.html',
  'public/privacy-policy.html',
  'public/terms-of-service.html',
  'public/data-deletion.html',
  'public/styles.css',
  'public/bundle.js',
  'public/builder-bundle.js',
  'public/js/richtext-vendor.js',
  'lib/builder/template.js',
  'lib/builder/email-template.js',
  'lib/builder/email-render.js',
];

function checkNoArtifactsStaged(files) {
  const offenders = files.filter((f) => GENERATED.includes(f));
  if (offenders.length) {
    failures.push(
      `Build artifacts must not be committed: ${offenders.join(', ')}\n` +
      '  These are generated by `npm run build` and gitignored — unstage them\n' +
      '  (git reset -- <file>). Vercel and CI rebuild them from source.'
    );
  }
}

function checkNoArtifactsTracked() {
  const tracked = sh('git ls-files -- ' + GENERATED.map((g) => `'${g}'`).join(' '))
    .split('\n').filter(Boolean);
  if (tracked.length) {
    failures.push(
      `Build artifacts are git-tracked but must not be: ${tracked.join(', ')}\n` +
      '  Fix: git rm --cached <file>  (they are rebuilt by `npm run build`)'
    );
  }
}

// ---------------------------------------------------------------------------
// 2. public/js freeze — no new .js files
// ---------------------------------------------------------------------------

function checkPublicJsFreeze(addedFiles) {
  const offenders = addedFiles.filter((f) => f.startsWith('public/js/') && f.endsWith('.js'));
  if (offenders.length) {
    failures.push(
      `public/js/ is frozen — new files are not allowed: ${offenders.join(', ')}\n` +
      '  New admin UI goes in components/ + lib/builder-client/ (see public/js/CLAUDE.md).'
    );
  }
}

// ---------------------------------------------------------------------------
// 3. No interactive elements inside <th>
// ---------------------------------------------------------------------------

const TH_BUTTON_RE = /<th\b[^>]*>(?:(?!<\/th>)[\s\S])*?<(?:button|a)[\s>]/i;

function checkButtonInTh() {
  if (MODE_ALL) {
    const files = sh("git ls-files 'src/pages/*.html' 'src/pages/**/*.html' 'public/js/*.js'")
      .split('\n').filter(Boolean);
    for (const file of files) {
      const content = require('fs').readFileSync(file, 'utf8');
      if (TH_BUTTON_RE.test(content)) {
        failures.push(`Interactive element inside <th> in ${file} — put the sort id on the <th>, not a nested button/link.`);
      }
    }
    return;
  }
  // Staged mode: only inspect added lines.
  const diff = sh('git diff --cached --unified=0 -- src/pages public/js components');
  const added = diff.split('\n').filter((l) => l.startsWith('+') && !l.startsWith('+++'));
  for (const line of added) {
    if (/<th\b[^>]*>\s*<(button|a)[\s>]/i.test(line)) {
      failures.push(`Interactive element inside <th> in staged change: ${line.slice(0, 120)}\n  Put the sort id on the <th> itself (see src/css/CLAUDE.md).`);
    }
  }
}

// ---------------------------------------------------------------------------

function main() {
  if (String(process.env.SKIP_CONVENTIONS || '') === '1') {
    console.log('[conventions] SKIP_CONVENTIONS=1 — checks bypassed.');
    return;
  }

  if (MODE_ALL) {
    checkNoArtifactsTracked();
    checkButtonInTh();
  } else {
    const files = stagedFiles();
    if (!files.length) return;
    // Deleting an artifact from tracking is allowed — only block add/modify.
    checkNoArtifactsStaged(stagedFiles('ACMR'));
    checkPublicJsFreeze(stagedFiles('A'));
    checkButtonInTh();
  }

  if (failures.length) {
    console.error('\n[conventions] Commit blocked — fix the following (or SKIP_CONVENTIONS=1 with a stated reason):\n');
    for (const f of failures) console.error(`  ✗ ${f}\n`);
    process.exit(1);
  }
  console.log('[conventions] All checks passed.');
}

main();
