#!/usr/bin/env node
'use strict';

/**
 * scripts/check_conventions.cjs — deterministic repo-convention checks.
 *
 * Default mode inspects the STAGED diff (runs from the pre-commit hook);
 * `--all` scans the working tree (for CI).
 *
 * Escape hatch: SKIP_CONVENTIONS=1 git commit ...   (or git commit --no-verify)
 * If you bypass, say so in the commit/PR description.
 *
 * Checks:
 *   1. No build artifacts staged — generated files are gitignored and must
 *      never be committed (Vercel/CI rebuild them from source).
 *   2. public/js/ freeze — no NEW .js files there (see public/js/CLAUDE.md).
 *   3. No <button>/<a> inside <th> (sort id goes on the <th> itself).
 *   4. UI doctrine checks — delegated to scripts/check_ui_doctrine.cjs
 *      (docs/MODULE_UI_DOCTRINE.md). Field strips, H/V margin pairing,
 *      breakpoint-only layout CSS, hex literals, the regenerated CSS layer.
 *   5. Retired AI model ids — delegated to scripts/check_model_ids.cjs.
 *
 * NOTE: in CI this whole script runs with continue-on-error (pre-existing
 * button-in-<th> violations), so it is ADVISORY there. Anything that must
 * actually block needs its own CI step as well — `npm run check:ui` and
 * `npm run check:models` are exactly that. Pre-commit does block, so checks
 * surfaced here still gate local commits.
 *
 * Generated-file list: keep in sync with .gitignore ("Build artifacts"
 * block), CLAUDE.md, and scripts/hooks/block_generated_edits.cjs.
 */

const { execSync } = require('child_process');

const MODE_ALL = process.argv.includes('--all');
const failures = [];

function sh(cmd) {
  return execSync(cmd, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
}

function stagedFiles(filter) {
  const flag = filter ? ` --diff-filter=${filter}` : '';
  return sh(`git diff --cached --name-only${flag}`).split('\n').map((s) => s.trim()).filter(Boolean);
}

// ---------------------------------------------------------------------------
// 1. Build artifacts must never be committed
// ---------------------------------------------------------------------------

const GENERATED = [
  'public/app-shell.html',
  'public/about.html',
  'public/site.html',
  'public/explore.html',
  'public/builder-preview.html',
  'public/privacy-policy.html',
  'public/terms-of-service.html',
  'public/data-deletion.html',
  'public/styles.css',
  'public/bundle.js',
  'public/builder-bundle.js',
  'public/js/richtext-vendor.js',
  'lib/builder/template.js',
  'lib/builder/email-template.js',
  'lib/builder/email-render.js',
  'lib/site-import/dist/normalize.js',
  'lib/site-import/dist/crawl.js',
  'lib/site-import/dist/capture-playwright.js',
];

function checkNoArtifactsStaged(files) {
  const offenders = files.filter((f) => GENERATED.includes(f));
  if (offenders.length) {
    failures.push(
      `Build artifacts must not be committed: ${offenders.join(', ')}\n` +
      '  These are generated by `npm run build` and gitignored — unstage them\n' +
      '  (git reset -- <file>). Vercel and CI rebuild them from source.'
    );
  }
}

function checkNoArtifactsTracked() {
  const tracked = sh('git ls-files -- ' + GENERATED.map((g) => `'${g}'`).join(' '))
    .split('\n').filter(Boolean);
  if (tracked.length) {
    failures.push(
      `Build artifacts are git-tracked but must not be: ${tracked.join(', ')}\n` +
      '  Fix: git rm --cached <file>  (they are rebuilt by `npm run build`)'
    );
  }
}

// ---------------------------------------------------------------------------
// 2. public/js freeze — no new .js files
// ---------------------------------------------------------------------------

function checkPublicJsFreeze(addedFiles) {
  const offenders = addedFiles.filter((f) => f.startsWith('public/js/') && f.endsWith('.js'));
  if (offenders.length) {
    failures.push(
      `public/js/ is frozen — new files are not allowed: ${offenders.join(', ')}\n` +
      '  New admin UI goes in components/ + lib/builder-client/ (see public/js/CLAUDE.md).'
    );
  }
}

// ---------------------------------------------------------------------------
// 3. No nested SORT control inside <th>
// ---------------------------------------------------------------------------
//
// House style (see public/js/assetPicker.js, which implements it): the sort id
// rides on the <th> itself and JS appends the arrow to textContent. A nested
// <button> gets the click but leaves the header cell itself inert, so keyboard
// and screen-reader users land on a control the table does not treat as the
// column header.
//
// This rule is about SORT controls only. It used to flag ANY <button>/<a> in a
// <th>, which made it a false-positive generator: bulk-action rows
// (.crud-bulk-actions), action-column buttons (.actions-col), header filter
// controls and go-links are all deliberate, documented patterns, and one match
// was a code comment describing the correct approach. Seven "violations" were
// six legitimate ones, which is exactly why this check sat behind
// continue-on-error in CI and stopped meaning anything.
//
// So: match a nested button/anchor only when its own id or class says "sort".

const TH_SORT_RE = /<th\b[^>]*>(?:(?!<\/th>)[\s\S])*?<(?:button|a)\b[^>]*(?:id|class)\s*=\s*["'][^"']*sort[^"']*["']/i;

function checkButtonInTh() {
  const advice = 'Put the sort id on the <th> itself and let JS append the arrow — see public/js/assetPicker.js.';
  if (MODE_ALL) {
    const files = sh("git ls-files 'src/pages/*.html' 'src/pages/**/*.html' 'public/js/*.js' 'components/**/*.tsx'")
      .split('\n').filter(Boolean);
    for (const file of files) {
      let content;
      try {
        content = require('fs').readFileSync(file, 'utf8');
      } catch {
        continue;
      }
      if (TH_SORT_RE.test(content)) {
        failures.push(`Nested sort control inside <th> in ${file} — ${advice}`);
      }
    }
    return;
  }
  // Staged mode: only inspect added lines.
  const diff = sh('git diff --cached --unified=0 -- src/pages public/js components');
  const added = diff.split('\n').filter((l) => l.startsWith('+') && !l.startsWith('+++'));
  for (const line of added) {
    if (TH_SORT_RE.test(line)) {
      failures.push(`Nested sort control inside <th> in staged change: ${line.trim().slice(0, 110)}\n  ${advice}`);
    }
  }
}

// ---------------------------------------------------------------------------

function main() {
  if (String(process.env.SKIP_CONVENTIONS || '') === '1') {
    console.log('[conventions] SKIP_CONVENTIONS=1 — checks bypassed.');
    return;
  }

  if (MODE_ALL) {
    checkNoArtifactsTracked();
    checkButtonInTh();
  } else {
    const files = stagedFiles();
    if (!files.length) return;
    // Deleting an artifact from tracking is allowed — only block add/modify.
    checkNoArtifactsStaged(stagedFiles('ACMR'));
    checkPublicJsFreeze(stagedFiles('A'));
    checkButtonInTh();
  }

  // UI doctrine (docs/MODULE_UI_DOCTRINE.md). Kept in its own module because
  // it needs a CSS parser; surfaced here so pre-commit and CI pick it up with
  // no extra wiring.
  const uiDoctrine = require('./check_ui_doctrine.cjs');
  const { failures: uiFailures, notes: uiNotes } = uiDoctrine.run({ all: MODE_ALL });
  for (const note of uiNotes) console.log(`[conventions] ${note}`);
  failures.push(...uiFailures);

  // Retired AI model ids. Also its own module, and — like check:ui — its own
  // BLOCKING CI step (`npm run check:models`), because this script runs under
  // continue-on-error in CI and a rule that only lives here can never fail a
  // build. Surfaced here as well so pre-commit catches it, where blocking works.
  const modelIds = require('./check_model_ids.cjs');
  const { failures: modelFailures, notes: modelNotes } = modelIds.run({ all: MODE_ALL });
  for (const note of modelNotes) console.log(`[conventions] ${note}`);
  failures.push(...modelFailures);

  // Machine-specific paths (vault doctrine/NODES.md P1). Own module and own
  // blocking CI step for the same reason as the two above — this script runs
  // advisory in CI — and surfaced here so pre-commit, which blocks, catches it
  // at the moment somebody types a path instead of deriving one.
  const machinePaths = require('./check_machine_paths.cjs');
  const { failures: pathFailures, notes: pathNotes } = machinePaths.run({ all: MODE_ALL });
  for (const note of pathNotes) console.log(`[conventions] ${note}`);
  failures.push(...pathFailures);

  // A vitest test that (transitively) requires a generated server lib passes
  // locally and always fails CI, because vitest runs before the build. Own
  // module; surfaced here so pre-commit catches it before it can ever be
  // pushed. It walks the whole test-file graph regardless of what is staged, so
  // there is no diff-mode shortcut — a change to a shared SOURCE can newly route
  // an untouched test into lib/builder/. See docs/DOCTRINE.md, CLAUDE.md #14.
  const vitestGeneratedLib = require('./check_vitest_generated_lib.cjs');
  const { failures: vitestFailures, notes: vitestNotes } = vitestGeneratedLib.run({ all: MODE_ALL });
  for (const note of vitestNotes) console.log(`[conventions] ${note}`);
  failures.push(...vitestFailures);

  if (failures.length) {
    console.error('\n[conventions] Commit blocked — fix the following (or SKIP_CONVENTIONS=1 with a stated reason):\n');
    for (const f of failures) console.error(`  ✗ ${f}\n`);
    process.exit(1);
  }
  console.log('[conventions] All checks passed.');
}

main();
