-- =============================================================================
-- APP Core Tables — run this in your Supabase SQL editor
-- Replaces store.json with proper persistent Supabase tables.
-- Safe to run multiple times (uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- contacts
-- The legacy MVP contact store, now in Supabase.
-- NOTE: New lead capture should use promo_leads. This table supports the
-- legacy Contacts/Segments/Campaigns pages until those are migrated (#2b).
-- ---------------------------------------------------------------------------
create table if not exists public.contacts (
  id          text        not null primary key,  -- keeps format "contact_<ts>_<rand>"
  email       text        not null unique,
  first_name  text        not null default '',
  last_name   text        not null default '',
  city        text        not null default '',
  tags        text[]      not null default '{}',
  created_at  timestamptz not null default now()
);

create index if not exists idx_contacts_email on public.contacts (email);

-- ---------------------------------------------------------------------------
-- segments
-- Saved filter definitions. Each segment stores its rules as JSONB so we
-- can add new rule types without schema changes.
-- ---------------------------------------------------------------------------
create table if not exists public.segments (
  id          text        not null primary key,
  name        text        not null,
  rules       jsonb       not null default '[]'::jsonb,
  definition  jsonb       null,                  -- social/advanced filter state
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- campaigns
-- Email campaign drafts and sent records.
-- ---------------------------------------------------------------------------
create table if not exists public.campaigns (
  id           text        not null primary key,
  name         text        not null,
  subject      text        not null,
  content      text        not null,
  segment_id   text        null references public.segments(id) on delete set null,
  status       text        not null default 'draft',
  sent_count   integer     not null default 0,
  created_at   timestamptz not null default now(),
  last_sent_at timestamptz null
);

-- ---------------------------------------------------------------------------
-- campaign_events
-- Open/click tracking per campaign per contact. Replaces store.events[].
-- ---------------------------------------------------------------------------
create table if not exists public.campaign_events (
  id          text        not null primary key,
  campaign_id text        not null references public.campaigns(id) on delete cascade,
  contact_id  text        not null,
  type        text        not null,              -- 'open' | 'click'
  created_at  timestamptz not null default now()
);

create index if not exists idx_campaign_events_campaign_id
  on public.campaign_events (campaign_id);

-- ---------------------------------------------------------------------------
-- assets
-- Reusable asset records for image/video/audio/lead magnet/screenshot.
-- ---------------------------------------------------------------------------
create table if not exists public.assets (
  id         bigint generated by default as identity primary key,
  asset_name text   not null,
  asset_type text   not null check (asset_type in ('Image', 'Video', 'Audio', 'Lead Magnet', 'Screenshot')),
  category   text   not null default '',
  location   text   not null default '',
  tags       text[] not null default '{}',
  size       bigint not null default 0,
  image_width integer null,
  image_height integer null
);

create table if not exists public.asset_categories (
  id         bigint generated by default as identity primary key,
  asset_type text        not null check (asset_type in ('Image', 'Video', 'Audio', 'Lead Magnet', 'Screenshot')),
  category   text        not null,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_asset_categories_type_category
  on public.asset_categories (asset_type, lower(category));

create table if not exists public.channels (
  id         bigint generated by default as identity primary key,
  channel    text        not null,
  user_name  text        not null,
  email      text        not null default '',
  password   text        not null default '',
  password_enc text      null,
  password_iv  text      null,
  password_tag text      null,
  key_version  text      null,
  created_at timestamptz not null default now()
);

alter table public.assets
  add column if not exists size bigint not null default 0;
alter table public.assets
  add column if not exists category text not null default '';
alter table public.assets
  add column if not exists image_width integer null;
alter table public.assets
  add column if not exists image_height integer null;
alter table public.assets
  add column if not exists id bigint generated by default as identity;
alter table public.asset_categories
  disable row level security;
alter table public.channels
  add column if not exists email text not null default '';
alter table public.channels
  add column if not exists password_enc text null;
alter table public.channels
  add column if not exists password_iv text null;
alter table public.channels
  add column if not exists password_tag text null;
alter table public.channels
  add column if not exists key_version text null;
alter table public.channels
  alter column password set default '';
alter table public.channels
  disable row level security;

update public.assets
set id = default
where id is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.assets'::regclass
      and contype = 'p'
  ) then
    alter table public.assets add primary key (id);
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Row Level Security — disable for service role key usage (app uses service key)
-- ---------------------------------------------------------------------------
alter table public.contacts       disable row level security;
alter table public.segments       disable row level security;
alter table public.campaigns      disable row level security;
alter table public.campaign_events disable row level security;
alter table public.assets         disable row level security;
