-- -----------------------------------------------------------------------------
-- dev_sessions_setup.sql
-- Table generation script to add Sessions to the "Ask Roger" Discussion Board
-- Run this block inside your Supabase SQL Editor.
-- -----------------------------------------------------------------------------

-- 1. Create the new dev_sessions table
CREATE TABLE IF NOT EXISTS public.dev_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT DEFAULT NULL, 
    name TEXT NOT NULL DEFAULT 'New Discussion',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE public.dev_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read/write/delete access on sessions" 
ON public.dev_sessions 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 3. Modify existing dev_chats table to strictly link to a session
-- WARNING: This deletes the existing disconnected chats to enforce the foreign key constraint
TRUNCATE TABLE public.dev_chats RESTART IDENTITY CASCADE;

-- 4. Add the foreign key to dev_chats
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
          AND table_name = 'dev_chats' 
          AND column_name = 'session_id'
    ) THEN
        ALTER TABLE public.dev_chats 
        ADD COLUMN session_id BIGINT REFERENCES public.dev_sessions(id) ON DELETE CASCADE NOT NULL;
    END IF;
END $$;

COMMENT ON TABLE public.dev_sessions IS 'Tri-Agent Discussion groups holding multiple chats';
