create table if not exists public.develop_module_classes (
  id bigint generated by default as identity primary key,
  name text not null,
  project_id text,
  owner_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_develop_module_classes_project_id
  on public.develop_module_classes (project_id);

create or replace function public.set_develop_module_classes_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_develop_module_classes_updated_at on public.develop_module_classes;

create trigger trg_develop_module_classes_updated_at
before update on public.develop_module_classes
for each row
execute function public.set_develop_module_classes_updated_at();

-- Add class_id to develop_modules if it doesn't exist
alter table public.develop_modules 
  add column if not exists class_id bigint;

-- Enforce foreign key constraint
alter table public.develop_modules
  drop constraint if exists fk_develop_modules_class_id;

alter table public.develop_modules
  add constraint fk_develop_modules_class_id
  foreign key (class_id) references public.develop_module_classes (id)
  on delete set null;
