create table if not exists public.develop_page_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  template_id text not null,
  primary_color text,
  background_color text,
  accent_color text,
  form_id text,
  lead_magnet_id text,
  headline_id text,
  pitch_id text,
  cta_id text,
  website_banner_image_id text,
  background_image_id text,
  feature_image_id text,
  highlight_image_id text,
  feature_headline_id text,
  feature_subheading_id text,
  feature_title text,
  feature_copy text,
  highlight_headline_id text,
  highlight_pitch_id text,
  highlight_title text,
  highlight_copy text,
  body_headline_id text,
  body_subheading_id text,
  body_pitch_id text,
  logo_wide_id text,
  logo_square_id text,
  content_overrides jsonb not null default '{}'::jsonb,
  project_id text,
  owner_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_develop_page_templates_project_id
  on public.develop_page_templates (project_id);

create index if not exists idx_develop_page_templates_template_id
  on public.develop_page_templates (template_id);

create or replace function public.set_develop_page_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_develop_page_templates_updated_at on public.develop_page_templates;
create trigger trg_develop_page_templates_updated_at
before update on public.develop_page_templates
for each row
execute function public.set_develop_page_templates_updated_at();
