-- messaging_topics table

create table if not exists public.messaging_topics (
  id bigint generated by default as identity primary key,
  topic text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_messaging_topics_topic
  on public.messaging_topics (topic);

create or replace function public.set_messaging_topics_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_messaging_topics_updated_at on public.messaging_topics;
create trigger trg_messaging_topics_updated_at
before update on public.messaging_topics
for each row
execute function public.set_messaging_topics_updated_at();
