create table if not exists public.messaging_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null,
  topic text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_messaging_keywords_keyword
  on public.messaging_keywords (keyword);

create index if not exists idx_messaging_keywords_topic
  on public.messaging_keywords (topic);

create unique index if not exists idx_messaging_keywords_keyword_topic
  on public.messaging_keywords (keyword, coalesce(topic, ''));

create or replace function public.set_messaging_keywords_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_messaging_keywords_updated_at on public.messaging_keywords;

create trigger trg_messaging_keywords_updated_at
before update on public.messaging_keywords
for each row
execute function public.set_messaging_keywords_updated_at();
