create table if not exists public.messaging_formats (
  id bigint generated by default as identity primary key,
  format text not null,
  family text not null,
  destination text,
  page_id text,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_messaging_formats_format
  on public.messaging_formats (format);

create index if not exists idx_messaging_formats_family
  on public.messaging_formats (family);

create or replace function public.set_messaging_formats_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_messaging_formats_updated_at on public.messaging_formats;

create trigger trg_messaging_formats_updated_at
before update on public.messaging_formats
for each row
execute function public.set_messaging_formats_updated_at();
