-- -----------------------------------------------------------------------------
-- roger_chat_setup.sql
-- Table generation script for the "Ask Roger" Tri-Agent Discussion Board
-- Run this block inside your Supabase SQL Editor.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.roger_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT DEFAULT NULL, -- Null if global/admin, or explicitly scoped to a project
    role TEXT NOT NULL,             -- 'user', 'model', or 'antigravity'
    content TEXT NOT NULL,          -- Markdown discussion text
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Enable RLS (Security)
ALTER TABLE public.roger_chats ENABLE ROW LEVEL SECURITY;

-- Create generous policies for Service Role access and Authenticated read/writes
CREATE POLICY "Allow authenticated read/write/delete access" 
ON public.roger_chats 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Optional: Since this is an internal tool, allow anon access if your platform relies heavily on Service proxying.
-- If the backend proxy accesses this via service_role, this RLS is bypassed entirely anyway.

-- Add a comment
COMMENT ON TABLE public.roger_chats IS 'Tri-Agent Discussion log for App Users, Roger Thorson, and Antigravity';
